//! The built-in manual: the text shown by Help ▸ Manual (`Ctrl+Shift+M`), as a list of sections a
//! reader moves between rather than one long scroll. Plain text with ASCII diagrams, so it
//! renders identically wherever CleeCode does — no font, no colour, no markdown.
//!
//! Body lines are kept under ~76 columns: the reading pane is the modal width minus the
//! section list, and wrapping mid-diagram would ruin the pictures.

use crate::i18n::Lang;

pub struct Section {
    pub title: &'static str,
    pub body: &'static [&'static str],
}

/// Where the reader is: which section, and how far down it. Held by `App` while the manual
/// is open.
pub struct ManualState {
    pub section: usize,
    pub scroll: usize,
}

impl ManualState {
    pub fn new() -> Self {
        ManualState { section: 0, scroll: 0 }
    }

    /// Moves to another section, always landing at its top — a scroll offset carried over
    /// from a longer section would open the next one part-way down.
    pub fn select(&mut self, index: usize, count: usize) {
        if count == 0 {
            return;
        }
        self.section = index.min(count - 1);
        self.scroll = 0;
    }

    pub fn cycle(&mut self, delta: isize, count: usize) {
        if count == 0 {
            return;
        }
        let len = count as isize;
        self.section = (((self.section as isize + delta) % len + len) % len) as usize;
        self.scroll = 0;
    }

    /// Scrolls within `len` lines shown `height` at a time, stopping at the last screenful
    /// rather than scrolling the text off the top.
    pub fn scroll_by(&mut self, delta: isize, len: usize, height: usize) {
        let max = len.saturating_sub(height.max(1));
        self.scroll = (self.scroll as isize + delta).clamp(0, max as isize) as usize;
    }
}

pub fn sections(lang: Lang) -> Vec<Section> {
    match lang {
        Lang::En => EN.iter().map(|(title, body)| Section { title, body }).collect(),
        Lang::It => IT.iter().map(|(title, body)| Section { title, body }).collect(),
    }
}

type Page = (&'static str, &'static [&'static str]);

const EN: &[Page] = &[
    ("Overview", &[
        "CleeCode is a terminal IDE: an editor, a file tree, and real terminals",
        "in one window. Everything is reachable with the keyboard alone; the",
        "mouse is an alternative, never the only way.",
        "",
        "  ┌─ menu bar ────────────────────────────────────────────────┐",
        "  │ CleeCode File Edit View Layout Run Terminal Workspace     │",
        "  ├──────────┬────────────────────────────────────────────────┤",
        "  │ Files    │ main.rs x  notes.md x        venv v    > Run   │",
        "  │  src/    ├────────────────────────────────────────────────┤",
        "  │   main.rs│  1  fn main() {                                │",
        "  │   ui.rs  │  2      println!(\"hello\");                     │",
        "  │  README  │  3  }                                          │",
        "  ├──────────┴─────────────────────┬──────────────────────────┤",
        "  │ Terminal 1                     │ claude                   │",
        "  │ $                              │ $ claude                 │",
        "  ├────────────────────────────────┴──────────────────────────┤",
        "  │ status message                                            │",
        "  └───────────────────────────────────────────────────────────┘",
        "",
        "Three frames take focus in turn: file tree, editor, terminals.",
        "  Ctrl+Alt+←↑↓→           go to the frame that lies that way",
        "  Ctrl+Tab                or cycle through them, like Cmd+Tab",
        "",
        "The focused frame is the one with the coloured border. Most keys",
        "are read by it, so the same key can mean different things in the",
        "editor and in a shell — which is why the terminal keeps almost all",
        "of them for the program running inside it.",
        "",
        "Two ways to find anything without remembering a shortcut:",
        "  Ctrl+P         command palette — every action, fuzzy-searched",
        "  Ctrl+Shift+B   the menu bar, then arrows and Enter",
    ]),
    ("Layout", &[
        "The layout is yours to shape, and it is remembered between runs.",
        "",
        "Show and hide frames:",
        "  Ctrl+E   file tree sidebar",
        "  Ctrl+J   terminal panel",
        "  Ctrl+B   menu bar (Ctrl+Shift+B still opens it while hidden)",
        "  Ctrl+L   split the editor into two panes",
        "",
        "Resize with the keyboard — Ctrl+Shift+U enters resize mode:",
        "  arrows         grow the focused frame on that side",
        "  Shift+arrow    shrink it",
        "  Esc / Enter    leave resize mode (sizes are saved)",
        "",
        "  ┌────────┬──────────────────┐   Editor focused, resize, ←",
        "  │ tree   ║ editor           │   moves the sidebar seam:",
        "  │        ║                  │   the editor grows, the tree",
        "  ├────────╨──────────────────┤   gives up columns.",
        "  │ terminals                 │",
        "  └───────────────────────────┘   A border that is the window",
        "                                  edge has nothing to move, and",
        "                                  says so in the status line.",
        "",
        "With the terminal focused and more than one terminal window open,",
        "the same arrows move the seam between the windows themselves —",
        "left/right when they sit side by side, up/down when stacked.",
        "",
        "With the mouse: drag any inner border. Same seams, same limits.",
        "",
        "Presets live in the Layout menu:",
        "  Classic   tree left, terminals as a strip below",
        "  Wide      no tree, terminals as a column on the right",
        "  Triple    tree left, editor centre, terminals right",
        "and 'Terminal on right' flips the terminal panel between the two",
        "orientations without touching anything else.",
        "",
        "The small button at the right-hand end of the menu bar fills in the",
        "background. A translucent terminal with a bright window behind it",
        "leaves the text barely readable; this paints CleeCode's own dark",
        "surface under everything until it is pressed again. View > Solid",
        "background is the same switch, and the choice is remembered.",
    ]),
    ("File tree", &[
        "The sidebar lists the project root. Icons come from a Nerd Font",
        "(clee --install-font installs the bundled one), and the dot on the",
        "right is git status: yellow modified, green added, red deleted,",
        "cyan renamed, grey untracked.",
        "",
        "With the tree focused (Ctrl+Alt+← from the editor):",
        "  ↑ ↓        move",
        "  → ←        expand / collapse a folder",
        "  Enter      open a file, or make a folder the project root",
        "  ..         the first row walks up to the parent folder",
        "  n / N      new file / new folder, in the selected directory",
        "  e          rename the selection",
        "  Delete     delete it (with a confirmation)",
        "  H          show or hide dotfiles",
        "",
        "A single click on a folder expands it, a double click reroots the",
        "project there. Right-click (or Ctrl+Shift+G) opens the same actions",
        "as a context menu.",
        "",
        "Files dragged onto the tree from elsewhere are copied into the",
        "selected directory. Dropped onto a terminal that is inside an ssh",
        "session, they are uploaded with scp instead.",
    ]),
    ("Editor", &[
        "Tabs across the top of the editor, one per open file; a * marks",
        "unsaved changes. Ctrl+O opens the fuzzy quick-open — start the query",
        "with / ~ ./ or ../ and it browses the filesystem instead of the",
        "project.",
        "",
        "  Ctrl+S / ^⇧S        save / save all",
        "  Ctrl+W              close the tab (asks about unsaved changes)",
        "  Ctrl+Shift+← / →   previous / next tab",
        "  Ctrl+Z / Ctrl+Y     undo / redo",
        "  Ctrl+C X V A        copy, cut, paste, select all",
        "  Ctrl+F / Ctrl+G     find and replace / go to line",
        "  Ctrl+K              comment or uncomment the line",
        "  Alt+↑ / Alt+↓       move the line up / down",
        "  Alt+Shift+↓         duplicate the line",
        "  Tab / Shift+Tab     indent / outdent the selection",
        "  Ctrl+Shift+F        fold or unfold the block under the cursor",
        "  Ctrl+Shift+X        run the selection, or the cell, in a live session",
        "  Alt+←/→             move by word (Shift extends the selection)",
        "  Ctrl+Backspace      delete the word before the cursor",
        "",
        "Two letters into a word, a short list drops under the cursor: the",
        "words already written in the open files, and the keywords of the",
        "language. It is not a box you have to answer. ↑↓ walk the list, Tab",
        "or Enter take the highlighted word, Esc dismisses it, and every",
        "other key goes on typing while the list narrows to what is left.",
        "The nearest words come first, then the ones further away, then the",
        "ones from the other open tabs; keywords are always last, because a",
        "keyword is quicker to type than a list is to walk. An accepted word",
        "is one undo step. Turn the whole thing off in settings",
        "(Ctrl+Shift+O) if a list that opens by itself is not help.",
        "",
        "If a language server for the file is installed, what it finds is",
        "underlined where it is — red for an error, yellow for a warning —",
        "the line number takes the same colour, and the message for the line",
        "you are on sits at the right of the status bar. Rust is the one",
        "language wired up so far, through rust-analyzer.",
        "",
        "It is told about an edit once you stop typing, not on every key: it",
        "re-reads the whole file each time, and eight of those for one word",
        "would be eight analyses of something half-written. If no server is",
        "installed CleeCode says so once and carries on exactly as before —",
        "and if one dies mid-session the underlines go, nothing else does.",
        "Nothing here can change the file: this reads and draws.",
        "",
        "Ctrl+Shift+X sends a piece of the file to an interpreter that is",
        "already running in one of the terminals, instead of starting a new",
        "one — so the session keeps its variables and a script is built up a",
        "piece at a time with the data already loaded. Octave and Python.",
        "",
        "What it sends is the selection, or, with nothing selected, the cell",
        "the cursor is in. A cell runs from a %% line to the next one; write",
        "it %% in Octave and # %% in Python, which is what both worlds write",
        "anyway. A file with no %% lines is one cell, so in a script nobody",
        "has divided it runs the script.",
        "",
        "It goes through a temporary file rather than being pasted at the",
        "prompt: a pasted indented block makes Python answer IndentationError,",
        "and at an Octave prompt it echoes line by line into your transcript.",
        "If no interpreter is running yet, it starts one — press it again and",
        "the second piece lands in that session.",
        "",
        "Find (Ctrl+F) takes the query literally and ignores case, which is",
        "what a search typed in a hurry usually means. Two keys change how it",
        "is read, and the box always says which way it currently is:",
        "",
        "  Ctrl+U   case matters",
        "  Ctrl+N   read the query as a regular expression",
        "",
        "Ctrl+Shift+D opens the git panel: three tabs, read-only. Changes",
        "is the diff of the file you are looking at (or of the whole tree",
        "with no file open), against the last commit, so staged and unstaged",
        "work both show. History is the last 50 commits; Branches lists them",
        "with the current one marked and how far each is from its upstream.",
        "Tab, ←→ or a click switch, ↑↓ scroll, R asks again, Esc closes. It",
        "reads the repository through git itself, so what it says is what",
        "the terminal beside it would say — hooks, signing, credential",
        "helpers and all.",
        "Nothing here writes: stage and commit in a shell, where you can see",
        "what happened.",
        "",
        "Ctrl+Shift+H asks the same question of the whole project. It reads",
        "the query the same way, with the same two keys, and the results are",
        "an ordinary list: type to narrow it further, Enter to open a file at",
        "that line with the cursor on the word. It starts from the selection",
        "or from what was last in the Find box, so searching for the word in",
        "front of you costs one key.",
        "",
        "With Ctrl+N on, the replacement can quote the groups back — search",
        "(\\w+)@(\\w+), replace $2.$1 — while a literal search leaves a $ as a",
        "dollar. Under the two fields the box shows the current match with",
        "the groups already filled in, and how many others would go the same",
        "way, so Ctrl+A can be read before it is pressed rather than judged",
        "after the file has changed.",
        "",
        "A pattern that will not compile, or one that gives up before",
        "finishing, says so in the box: half-typed is not the same as no",
        "matches, and the two want different fixes.",
        "",
        "Split view (Ctrl+L) gives two panes, each with its own tab strip:",
        "",
        "  ┌───────────────┬───────────────┐  Alt+← / Alt+→ move between",
        "  │ main.rs       │ notes.md      │  the panes. Both run their own",
        "  │               ║               │  file with ▶ Run; the",
        "  │               ║               │  ║ seam is draggable too.",
        "  └───────────────┴───────────────┘",
        "",
        "Files changed on disk are reloaded automatically unless the buffer",
        "has unsaved changes, in which case the local version is kept and the",
        "status line says so.",
        "",
        "Scrollbars run down the last column (and along the last row) inside",
        "the frame. They appear while the view is moving — however it moves,",
        "by wheel, arrows or Go to line — and again the moment the pointer",
        "rests on one; otherwise they fade out. The one along the bottom only",
        "shows with word wrap off: wrapped text has nowhere sideways to go.",
        "",
        "Idle it is just a thumb, marking where you are. Point at it and it",
        "becomes a control:",
        "",
        "  · drag the thumb to scroll, and it keeps following the pointer",
        "    even if it wanders off the bar",
        "  · click anywhere on the groove to jump there",
        "  · the ▴ ▾ (and ◂ ▸) at the ends move one line per click — the",
        "    arrow keys' job, done with the mouse",
        "",
        "They are inside the frame, not on its border, because the border is",
        "already the seam you drag to resize: two controls sharing a column",
        "would make aiming at either a gamble. So a showing bar lies over the",
        "last column of text. Nothing to scroll means no bar at all, and that",
        "column is ordinary text again.",
    ]),
    ("Terminals", &[
        "The terminals are real ptys running your $SHELL, so ssh, vim, tmux",
        "and claude all behave as they would anywhere else.",
        "",
        "There are two levels, and it is worth keeping them apart:",
        "",
        "  window   a tiled pane. Ctrl+Shift+N opens one.",
        "  tab      a shell inside a window. Ctrl+Shift+T opens one, and",
        "           it. Tabs only show a strip once a window has two.",
        "",
        "  ┌ Terminal 1 ─────────────┬ claude ─┬ octave ──┬───────────────┐",
        "  │ $                       │ the second window has three tabs,  │",
        "  │                         │ each one its own shell; one of them│",
        "  │                         │ is on screen at a time.            │",
        "  └─────────────────────────┴────────────────────────────────────┘",
        "",
        "  Ctrl+Shift+↑ / ↓       previous / next window",
        "  Ctrl+Shift+← / →       previous / next tab in this window",
        "  Ctrl+Shift+E            name this terminal, and give it a",
        "                          startup command",
        "",
        "Ctrl+Shift+E opens a small form, two fields (Tab switches):",
        "",
        "  Name              claude",
        "  Startup command   claude",
        "",
        "The name replaces 'Terminal N' in the title or tab strip. The",
        "startup command is remembered with the workspace and run in this",
        "shell whenever that workspace is opened — see the Workspaces",
        "section. Setting it does not run it on the spot.",
        "",
        "Selecting text: drag with the mouse, or hold Shift and use the",
        "arrows. Either way the selection goes straight to the system",
        "clipboard, and Esc clears it. Paste with the context menu (the",
        "shell needs Ctrl+V for itself).",
        "",
        "Scrolling back: the wheel over a pane walks through what has",
        "scrolled off it, Shift+PageUp/PageDown does the same a screen at a",
        "time, and typing anything jumps back to the live output. A bar down",
        "the pane's last column shows where you are — draggable, clickable,",
        "with step arrows at the ends, exactly like the editor's.",
        "",
        "Output that arrives while you are reading back does not drag the",
        "page away from you: the view stays on the lines you are looking at.",
        "",
        "How much is kept is `terminal_scrollback` in settings.toml, 2000",
        "lines by default. It is not free — a shell holds whole rows of",
        "cells, so the cost is lines x columns x 32 bytes, and every tab pays",
        "it separately. A shell reads the setting when it starts, so a change",
        "reaches the next shell you open, not the ones already running.",
        "",
        "While a full-screen program (vim, less, htop, Claude Code) has the",
        "screen, there is no history of ours to walk: it scrolls a view of",
        "its own. If it asked for mouse events — most of them do — the wheel",
        "is handed to it, notch by notch, and Shift+PageUp goes to it too, so",
        "it scrolls the way it does in any other terminal. What it does with",
        "them is its business: a program that does not scroll on the wheel",
        "will not start doing so here.",
        "",
        "A shell that exits closes its tab, and a window with no tabs left",
        "disappears. There is always at least one terminal.",
    ]),
    ("Workspaces", &[
        "A workspace is a saved snapshot of a whole set-up:",
        "",
        "  · the project root and the files open in tabs",
        "  · frame sizes, which frames are shown, split view",
        "  · every terminal window and tab, with its name, its startup",
        "    command and its share of the space",
        "  · the selected Python venv",
        "",
        "  Workspace ▸ Save workspace...    Ctrl+Shift+W, then a name",
        "  Workspace ▸ Open workspace...    pick from the saved ones",
        "  Workspace ▸ Delete workspace...  same list, removes one",
        "",
        "Opening one rebuilds the terminals it describes and runs each",
        "startup command in its own shell. A workspace with a shell named",
        "'claude' whose startup command is 'claude', next to a plain one and",
        "an 'octave' tab, comes back exactly like that every time:",
        "",
        "  ┌ claude ──────────────┬ Terminal 2 ──┬ octave ──────────────┐",
        "  │ $ claude             │ $            │ $ octave             │",
        "  │ ▌                    │              │ octave:1>            │",
        "  └──────────────────────┴──────────────┴──────────────────────┘",
        "",
        "Buffers with unsaved changes are never closed by opening a",
        "workspace — they stay open alongside its files.",
        "",
        "The workspace in use is written back when CleeCode exits, so",
        "renaming a terminal or nudging a seam is still there next time, and",
        "a bare `clee` reopens it. Launching with a path argument starts",
        "from that path instead and leaves the workspace alone.",
        "",
        "Changing the project folder — Enter on a directory in the tree, or",
        "going up from it — steps out of the workspace: the badge clears and",
        "its file is left exactly as it was, describing the project you came",
        "from. Open it again from the Workspace menu, in any folder, to go",
        "back. The built-in layout is the exception: it belongs to no",
        "project, so it stays with you.",
        "",
        "Each workspace is a plain TOML file under the config directory",
        "(workspaces/<name>.toml), so they can be edited, copied between",
        "machines, or kept in a dotfiles repository.",
        "",
        "Three workspaces are built in and are not files: Default layout,",
        "which puts the frames back the way CleeCode ships them, and two",
        "that set up a numeric session:",
        "",
        "  clee -w octave    an Octave prompt, already running",
        "  clee -w pylab     a Python one, in the active venv if there is one",
        "",
        "Each opens one terminal window with two tabs — the interpreter, and",
        "a plain shell for git and pip. A second window would take screen",
        "from the editor permanently to hold something used a minute at a",
        "time; a tab is one keystroke away and costs nothing.",
        "",
        "Each also opens a second terminal window showing the workspace:",
        "the variables in that session, with their size, range and mean.",
        "It fills in by itself whenever a command finishes — nothing is",
        "typed at your prompt to ask, so your transcript stays yours and a",
        "busy interpreter is never interrupted. A window rather than a tab,",
        "because the point is to glance at it while you work.",
        "",
        "A plot opens as a tab beside the script that drew it, and no window",
        "opens anywhere: a live figure window cannot be moved into a",
        "terminal, so the session is told to open none and hands over a",
        "picture instead. Re-plot and the tab changes with it; a second",
        "figure is a second tab. It never takes the keyboard from what you",
        "were writing.",
        "",
        "Nothing is installed and nothing is written to your home directory.",
        "The interpreter is handed the code and a path to write to through",
        "its environment, and outside CleeCode none of it does anything.",
        "",
        "The prompt goes beside the editor when the window is wide enough",
        "for both, which is where the Octave and MATLAB desktops put it and",
        "for the same reason: numeric output is wide, and a matrix row wraps",
        "into nonsense in a narrow pane. Under about 150 columns it goes",
        "underneath instead, so neither frame is squeezed.",
        "",
        "Those three names are reserved, and saving over one is refused. A",
        "workspace of your own that already had the name still opens and",
        "still wins — CleeCode says so, so you can rename yours if it is the",
        "preset you were after.",
    ]),
    ("Running code", &[
        "▶ Run in the toolbar, or Ctrl+Shift+R, runs the focused editor's file",
        "pane: the command is typed into an idle terminal, so its output,",
        "prompts and errors are just shell output you can scroll and copy.",
        "",
        "The button left of ▶ Run answers, for the file you are looking at,",
        "what Run will use on it — and lets you change it. What it offers",
        "follows the extension, so it is never a control that does nothing:",
        "",
        "  · On a .py file it is the Python venv selector: the venvs found in",
        "    the project root, plus any you register from elsewhere on disk",
        "    (by path, or with the folder browser). The selected one replaces",
        "    python/python3 in the run command, and is remembered per",
        "    workspace. A venv means nothing to any other interpreter, which",
        "    is why it is offered nowhere else.",
        "  · On every file type, including .py, the last entry opens the run",
        "    command for that extension. That is how a file type nobody",
        "    thought of — .tex, .rs, .sql — gets one.",
        "",
        "A command can live in either of two files, and the menu offers both",
        "with a ● on whichever one Run would actually use:",
        "",
        "  settings.toml     shared by every project",
        "  .cleecode.toml    in the project root, and only for it",
        "",
        "The project file wins where it says anything. It is what lets one",
        "project typeset its own master file — latexmk -pdf thesis.tex —",
        "while every other .tex still runs the shared command. Emptying that",
        "box drops the override and hands the extension back; empty the",
        "shared one instead and the built-in default returns.",
        "",
        ".cleecode.toml belongs to the project, so it is meant to be",
        "committed: everyone who opens the folder gets the same commands.",
        "It is removed when its last override goes, rather than left behind",
        "as an empty file.",
        "",
        "Both use the same [run_commands] table, keyed by extension, and the",
        "box writes to exactly that:",
        "",
        "  [run_commands]",
        "  py  = \"python3 {file}\"",
        "  m   = \"octave --persist {file}\"",
        "  tex = \"pdflatex -output-directory {dir} {file}\"",
        "",
        "Four placeholders, each quoted so paths with spaces survive:",
        "",
        "  {file}  the whole path        {name}  the file name",
        "  {dir}   the folder it is in   {stem}  that name without .ext",
        "",
        "The command is typed at a real shell, so steps chain the way they",
        "read: \"pdflatex {file} && open {dir}/{stem}.pdf\".",
        "",
        "Pictures can also be run: .png, .jpg, .gif and .webp have a command",
        "that shows them in a terminal pane with chafa. That is not how they",
        "open, though — see the Pictures section — it is there for when you",
        "want one in a terminal rather than in a tab. Any other file that",
        "isn't text but does have a command runs on opening. The",
        "-f symbols in that command is load-bearing — left to itself chafa",
        "asks the host terminal what it can do, gets told 'graphics', and",
        "sends a picture a pane cannot pass on, leaving it blank. A picture",
        "taller than the pane can simply be scrolled back to.",
        "",
        "Two special cases save a lot of annoyance:",
        "",
        "  · An interpreter installed outside PATH goes under",
        "    [interpreter_paths] (program name -> absolute path). Octave on",
        "    Windows is found automatically in Program Files.",
        "  · If an Octave prompt is already open in a terminal, a .m file is",
        "    handed to that session with run(...) instead of starting a",
        "    second interpreter — the variables and plot windows survive.",
    ]),
    ("Pictures", &[
        "A picture opens in a tab and is drawn there. Nothing in it can be",
        "edited, so no buffer is made for it: the tab is the picture.",
        "",
        "  .png .jpg .jpeg .gif .webp .bmp .ico .tiff",
        "",
        "How well it is drawn depends on the terminal CleeCode is running in.",
        "Where there is a graphics protocol — kitty, iTerm2, sixel — those are",
        "real pixels. Where there is not, it falls back to coloured",
        "half-blocks. The status line names which one you got when the tab",
        "opens, so a coarse picture is never a mystery.",
        "",
        "The pixels are drawn by CleeCode itself, not by a program inside a",
        "terminal pane. A pane cannot show them at all: it is parsed into a",
        "grid of cells and repainted, and graphics escape sequences do not",
        "survive that. Drawn from the editor they go straight out the way",
        "everything else does — which is also why this still works over ssh.",
        "",
        "Large pictures are decoded on a background thread, so opening one",
        "never stalls the window or the shells in it. Anything absurdly large",
        "is refused with a message rather than attempted.",
        "",
        "In split view a picture opens in the pane you are not working in, so",
        "the file you came from stays visible. The layout itself is never",
        "rearranged for you.",
    ]),
    ("Markdown", &[
        "A markdown file opens as text, because that is what you do with one.",
        "\u{25b6} Run beside it shows it rendered, in the other half of the",
        "editor — splitting it if it was not already, since asking for a",
        "preview is asking to see two things at once.",
        "",
        "Two tabs, one file, and one copy of the text: the rendered tab owns",
        "nothing, it is a view of the buffer you are typing in. They cannot",
        "disagree about what the file says, and closing the source closes the",
        "view with it. In the strip they are told apart by a glyph:",
        "",
        "  guida.md      the source, the one you edit",
        "  \u{25a4} guida.md    the rendered view",
        "",
        "It follows what you type. Where the terminal can draw pictures and",
        "pandoc is installed, the rendering is a real document: proper fonts,",
        "and pictures the text refers to appearing in the flow of it, which a",
        "grid of characters cannot do. That takes about half a second, so it",
        "waits for you to stop typing rather than chasing each keystroke.",
        "",
        "Without one of those, it falls back to styled terminal text —",
        "headings, lists, quotes, code blocks, emphasis. Coarser, but it",
        "keeps up with the keys and it works over ssh on anything.",
        "",
        "\u{25b6} Run on a rendered tab says Refresh instead, and forces it.",
        "",
        "Every preview carries a bar along its bottom. The buttons are also",
        "keys — a preview holds no text, so plain letters were free:",
        "",
        "  \u{2190} \u{2192}    the page before / after (documents)",
        "  g      go to a page",
        "  + -    zoom in / out",
        "  f      fit the whole page",
        "  w      fit its width, which is what you want for reading",
        "  d      dark: the page inverted, for a light document at night",
        "  i      invert: the same, on a picture, where it is a negative",
        "  t      text: markdown as styled text rather than a document",
        "",
        "Dark is remembered, separately for PDFs and for markdown — a paper",
        "and a README are read in different places — so turning it on once",
        "means the next one of that kind opens that way too. A picture is",
        "neither: inverting a photograph is not a mode but a negative of that",
        "one image, so it is called invert, it belongs to the tab, and it is",
        "never carried to the next picture.",
        "",
        "The text button is markdown's alone, and only where a document could",
        "be made at all: it switches between the two renderings, and it is",
        "remembered like the rest. Over styled text the bar carries nothing",
        "else — there are no pixels there to zoom, fit or darken.",
        "",
        "Zoomed past the pane, a page is scrolled rather than shrunk: the",
        "wheel and the arrows move the window over it, scrollbars show where",
        "on the page you are and can be dragged, and Ctrl with the wheel",
        "zooms instead of moving.",
    ]),
    ("PDFs", &[
        "A PDF opens as pages, one at a time, drawn the same way a picture",
        "is — real pixels where the terminal has a graphics protocol.",
        "",
        "  \u{2190} \u{2191}   the page before",
        "  \u{2192} \u{2193}   the page after",
        "",
        "The plain arrows, with no chord to remember: there is no text in the",
        "tab for a cursor to move through, so they were free. Which page you",
        "are on is written along the bottom of the frame.",
        "",
        "Pages are rasterised by pdftoppm (poppler) or, failing that, by",
        "ghostscript — whichever is installed. Neither is bundled: a PDF",
        "renderer that CleeCode could link is either under a licence this",
        "project cannot take or a prebuilt binary blob per platform. With",
        "neither installed the tab says so rather than sitting empty. A TeX",
        "distribution brings ghostscript with it, so if you are here for",
        "LaTeX you already have one.",
        "",
        "A PDF that changes on disk is re-rendered where it stands, on the",
        "page you were reading. That is the LaTeX loop: edit the source,",
        "press \u{25b6} Run, and the page beside it becomes the page you just",
        "typeset — with the source still on screen, if you split the editor",
        "first.",
    ]),
    ("Keys", &[
        "Frame navigation is Ctrl+Alt and an arrow, not plain Ctrl: macOS gives",
        "Ctrl with every arrow to Mission Control and to switching Spaces, and",
        "takes them before any terminal sees them.",
        "",
        "There are no function keys and no PageUp/PageDown here: on a laptop",
        "both need Fn. Ctrl+Shift+<letter> is the application's own layer, and",
        "it is safe in a terminal — no terminal can send Ctrl+Shift to the",
        "program running in a pane, so nothing there is listening for it.",
        "",
        "General",
        "  Ctrl+Shift+M            this manual",
        "  Ctrl+Shift+B            menu bar",
        "  Ctrl+Shift+O            settings",
        "  Ctrl+Shift+G            context menu for the focused frame",
        "  Ctrl+P / Ctrl+O         command palette / quick open",
        "  Ctrl+Q                  quit",
        "",
        "Focus and layout",
        "  Ctrl+Alt+←↑↓→           go to the frame in that direction",
        "  Ctrl+Tab                or cycle them, like Cmd+Tab",
        "  Ctrl+Shift+← / →        previous / next tab of this frame",
        "  Ctrl+E / Ctrl+J         sidebar / terminal panel",
        "  Ctrl+B / Ctrl+L         menu bar / split editor",
        "  Alt+← / Alt+→           move between split panes",
        "  Ctrl+Shift+U            resize mode",
        "",
        "Files and editing",
        "  Ctrl+S / Ctrl+Shift+S   save / save all",
        "  Ctrl+W / Ctrl+D         close tab",
        "  Ctrl+Z / Ctrl+Y         undo / redo",
        "  Ctrl+F / Ctrl+G         find and replace / go to line",
        "  Ctrl+U / Ctrl+N         in Find: case / regex",
        "  Ctrl+Shift+H            search the whole project",
        "  Ctrl+Shift+D            git panel (changes, history, branches)",
        "  Ctrl+K                  toggle comment",
        "  ↑↓ Tab Enter Esc        in the completion list, while it is up",
        "  Alt+↑ / Alt+↓           move line       Alt+Shift+↓  duplicate",
        "  Ctrl+Shift+F            fold / unfold",
        "",
        "Terminals",
        "  Ctrl+Shift+T            new tab",
        "  Ctrl+Shift+K            close this shell (and its window if last)",
        "  Ctrl+Shift+N            new window",
        "  Ctrl+Shift+↑ / ↓        previous / next window",
        "  Ctrl+Shift+E            name and startup command",
        "  Shift+arrows            select text (copies as you go)",
        "",
        "Workspaces and running",
        "  Ctrl+Shift+R            run the current file",
        "  Ctrl+Shift+X            run the selection or the cell",
        "  Ctrl+Shift+W            save the workspace",
        "",
        "In the file tree: n / N new file / folder, e rename, Delete remove,",
        "H hidden files, Enter open or reroot.",
        "",
        "The only Alt chords left are the arrows, and they work everywhere:",
        "an Option arrow makes no printable character, so every terminal",
        "forwards it as Meta whatever the keyboard layout is.",
    ]),
    ("Files", &[
        "Everything CleeCode keeps lives in one directory:",
        "",
        "  ~/.config/cleecode/            (macOS and Linux)",
        "  %APPDATA%\\cleecode\\             (Windows)",
        "",
        "    settings.toml                preferences, layout, run commands,",
        "                                 registered venvs, last session",
        "    workspaces/<name>.toml       one file per saved workspace",
        "",
        "settings.toml is meant to be edited by hand. The parts that have no",
        "panel in the app are all there: [run_commands], [interpreter_paths],",
        "registered_venvs, auto_pairs, completion, diagnostics,",
        "diagnostics_figures.",
        "",
        "The settings panel (Ctrl+Shift+O) covers line numbers, highlighting,",
        "word wrap, tab size, spaces versus tabs, whitespace marks,",
        "auto-indent, mouse capture and the interface language. Changes take",
        "effect at once and are saved on exit.",
        "",
        "Command line:",
        "  clee                  resume the last workspace or project",
        "  clee <directory>      open it as the project root",
        "  clee <file>           open the file in the current directory",
        "  clee --install-font   install the bundled Nerd Font",
        "  clee --help           usage, --version",
    ]),
];

const IT: &[Page] = &[
    ("Panoramica", &[
        "CleeCode è una IDE da terminale: editor, albero dei file e terminali",
        "veri in una sola finestra. Tutto è raggiungibile da tastiera; il",
        "mouse è un'alternativa, mai l'unica strada.",
        "",
        "  ┌─ barra dei menu ──────────────────────────────────────────┐",
        "  │ CleeCode File Modifica Vista Layout Esegui Terminale Aiuto│",
        "  ├──────────┬────────────────────────────────────────────────┤",
        "  │ File     │ main.rs x  note.md x       venv v    > Esegui  │",
        "  │  src/    ├────────────────────────────────────────────────┤",
        "  │   main.rs│  1  fn main() {                                │",
        "  │   ui.rs  │  2      println!(\"ciao\");                      │",
        "  │  README  │  3  }                                          │",
        "  ├──────────┴─────────────────────┬──────────────────────────┤",
        "  │ Terminale 1                    │ claude                   │",
        "  │ $                              │ $ claude                 │",
        "  ├────────────────────────────────┴──────────────────────────┤",
        "  │ messaggio di stato                                        │",
        "  └───────────────────────────────────────────────────────────┘",
        "",
        "Tre frame prendono il focus a turno: albero, editor, terminali.",
        "  Ctrl+Alt+←↑↓→           va al frame in quella direzione",
        "  Ctrl+Alt+←↑↓→           va al frame in quella direzione",
        "  Ctrl+Tab                oppure li scorre a turno",
        "",
        "Il frame con il bordo colorato è quello che ha il focus: quasi tutti",
        "i tasti li legge lui, quindi lo stesso tasto può voler dire cose",
        "diverse nell'editor e in una shell — per questo il terminale lascia",
        "passare quasi tutto al programma che ci gira dentro.",
        "",
        "Due modi per trovare qualsiasi cosa senza ricordare scorciatoie:",
        "  Ctrl+P         palette comandi — ogni azione, ricerca fuzzy",
        "  Ctrl+Shift+B   la barra dei menu, poi frecce e Invio",
    ]),
    ("Layout", &[
        "Il layout si modella come si vuole e viene ricordato fra un avvio",
        "e l'altro.",
        "",
        "Mostrare e nascondere i frame:",
        "  Ctrl+E   sidebar dei file",
        "  Ctrl+J   pannello terminali",
        "  Ctrl+B   barra dei menu (Ctrl+Shift+B la apre comunque)",
        "  Ctrl+L   divide l'editor in due pannelli",
        "",
        "Da tastiera — Ctrl+Shift+U entra in modalità ridimensiona:",
        "  frecce         allargano il frame sotto focus da quel lato",
        "  Shift+freccia  lo restringono",
        "  Esc / Invio    esce (le dimensioni vengono salvate)",
        "",
        "  ┌────────┬──────────────────┐   Editor sotto focus, poi ←",
        "  │ albero ║ editor           │   muove la giunzione con la",
        "  │        ║                  │   sidebar: l'editor cresce,",
        "  ├────────╨──────────────────┤   l'albero cede colonne.",
        "  │ terminali                 │",
        "  └───────────────────────────┘   Un bordo che è il bordo della",
        "                                  finestra non si muove, e la",
        "                                  status line lo dice.",
        "",
        "Con il terminale sotto focus e più finestre terminale aperte, le",
        "stesse frecce muovono la giunzione fra le finestre: sinistra/destra",
        "se sono affiancate, su/giù se impilate.",
        "",
        "Col mouse: trascina un bordo interno. Stesse giunzioni, stessi",
        "limiti.",
        "",
        "I preset stanno nel menu Layout:",
        "  Classico   albero a sinistra, terminali in fascia sotto",
        "  Ampio      niente albero, terminali in colonna a destra",
        "  Triplo     albero a sinistra, editor al centro, terminali a destra",
        "e 'Terminale a destra' ribalta il pannello fra i due orientamenti.",
        "",
        "Il pulsantino all'estremità destra della barra dei menu riempie lo",
        "sfondo. Un terminale trasparente con dietro una finestra chiara",
        "rende il testo quasi illeggibile: questo stende sotto tutto la",
        "superficie scura di CleeCode finché non lo premi di nuovo. Vista >",
        "Sfondo pieno fa lo stesso, e la scelta viene ricordata.",
    ]),
    ("Albero file", &[
        "La sidebar mostra la radice del progetto. Le icone vengono da un",
        "Nerd Font (clee --install-font installa quello incluso) e il pallino",
        "a destra è lo stato git: giallo modificato, verde aggiunto, rosso",
        "eliminato, ciano rinominato, grigio non tracciato.",
        "",
        "Con l'albero sotto focus (Ctrl+Alt+← dall'editor):",
        "  ↑ ↓        muove",
        "  → ←        espande / chiude una cartella",
        "  Invio      apre un file, o rende una cartella la radice",
        "  ..         la prima riga risale alla cartella superiore",
        "  n / N      nuovo file / nuova cartella nella directory scelta",
        "  e          rinomina",
        "  Canc       elimina (con conferma)",
        "  H          mostra o nasconde i file nascosti",
        "",
        "Un clic su una cartella la espande, un doppio clic ci sposta la",
        "radice del progetto. Il tasto destro (o Ctrl+Shift+G) apre le stesse",
        "azioni come menu contestuale.",
        "",
        "I file trascinati sull'albero vengono copiati nella directory",
        "selezionata; se il drop avviene su un terminale dentro una sessione",
        "ssh, vengono invece caricati con scp.",
    ]),
    ("Editor", &[
        "In cima all'editor una tab per file aperto; un * segnala le",
        "modifiche non salvate. Ctrl+O apre la ricerca rapida fuzzy — se la",
        "query inizia con / ~ ./ o ../ diventa un browser del filesystem.",
        "",
        "  Ctrl+S / ^⇧S        salva / salva tutto",
        "  Ctrl+W              chiude la tab (chiede se ci sono modifiche)",
        "  Ctrl+Shift+← / →   tab precedente / successiva",
        "  Ctrl+Z / Ctrl+Y     annulla / ripeti",
        "  Ctrl+C X V A        copia, taglia, incolla, seleziona tutto",
        "  Ctrl+F / Ctrl+G     trova e sostituisci / vai alla riga",
        "  Ctrl+K              commenta o decommenta la riga",
        "  Alt+↑ / Alt+↓       sposta la riga su / giù",
        "  Alt+Shift+↓         duplica la riga",
        "  Tab / Shift+Tab     aumenta / riduce il rientro",
        "  Ctrl+Shift+F        comprime o espande il blocco",
        "  Ctrl+Shift+X        esegue la selezione, o la cella, in una sessione viva",
        "  Alt+←/→             si muove per parole (Shift estende)",
        "  Ctrl+Backspace      cancella la parola precedente",
        "",
        "Dopo due lettere di una parola compare sotto il cursore una lista",
        "breve: le parole già scritte nei file aperti, più le parole chiave",
        "del linguaggio. Non è un riquadro a cui rispondere. ↑↓ scorrono,",
        "Tab o Invio prendono la parola evidenziata, Esc la fa sparire, e",
        "ogni altro tasto continua a scrivere mentre la lista si restringe",
        "su quello che resta. Vengono prima le parole più vicine al cursore,",
        "poi quelle lontane, poi quelle delle altre schede; le parole chiave",
        "sempre per ultime, perché si scrivono più in fretta di quanto si",
        "scorra una lista. Una parola accettata è un solo passo di undo. Si",
        "spegne dalle impostazioni (Ctrl+Shift+O) se una lista che si apre da",
        "sola non è un aiuto.",
        "",
        "Se sul computer c'è un language server per il file, quello che trova",
        "viene sottolineato dov'è — rosso per un errore, giallo per un",
        "avviso — il numero di riga prende lo stesso colore, e il messaggio",
        "della riga dove sei sta a destra nella barra di stato. Per ora l'unico",
        "linguaggio agganciato è Rust, tramite rust-analyzer.",
        "",
        "La modifica gli viene detta quando smetti di scrivere, non a ogni",
        "tasto: rilegge il file intero ogni volta, e otto tasti per una parola",
        "sarebbero otto analisi di una cosa scritta a metà. Se il server non",
        "è installato CleeCode lo dice una volta e prosegue esattamente come",
        "prima; se muore a metà sessione spariscono le sottolineature, non",
        "altro. Da qui non si tocca il file: si legge e si disegna.",
        "",
        "Ctrl+Shift+X manda un pezzo del file a un interprete già aperto in",
        "uno dei terminali, invece di avviarne un altro — così la sessione",
        "si tiene le variabili e uno script si costruisce un pezzo per volta",
        "coi dati già caricati. Octave e Python.",
        "",
        "Manda la selezione, o, se non c'è selezione, la cella dove sta il",
        "cursore. Una cella va da una riga %% alla successiva; si scrive %%",
        "in Octave e # %% in Python, che è quello che si scrive già in",
        "entrambi i mondi. Un file senza righe %% è una cella sola, quindi in",
        "uno script non diviso esegue lo script.",
        "",
        "Passa da un file temporaneo invece di incollare al prompt: un blocco",
        "indentato incollato fa rispondere IndentationError a Python, e a un",
        "prompt Octave viene riecheggiato riga per riga nella trascrizione.",
        "Se nessun interprete è ancora aperto, ne avvia uno — premi di nuovo",
        "e il secondo pezzo finisce in quella sessione.",
        "",
        "Trova (Ctrl+F) prende la query alla lettera e ignora maiuscole e",
        "minuscole, che è quello che di solito si intende cercando di fretta.",
        "Due tasti cambiano come viene letta, e il riquadro dice sempre come",
        "sta leggendo adesso:",
        "",
        "  Ctrl+U   le maiuscole contano",
        "  Ctrl+N   legge la query come espressione regolare",
        "",
        "Ctrl+Shift+D apre il pannello Git: tre schede, in sola lettura.",
        "Modifiche è il diff del file che stai guardando (o dell'intero",
        "albero se non ne hai aperto uno) rispetto all'ultimo commit, quindi",
        "si vede sia quello in stage sia quello no. Cronologia sono gli",
        "ultimi 50 commit; Branch li elenca con quello corrente marcato e la",
        "distanza dal suo upstream. Tab, ←→ o un click cambiano scheda, ↑↓",
        "scorrono, R richiede, Esc chiude. Legge il repository tramite git",
        "stesso, così quello che dice è quello che direbbe il terminale",
        "accanto — hook, firma e credential helper compresi. Qui non si",
        "scrive niente: stage e commit si fanno in una shell, dove vedi",
        "cos'è successo.",
        "",
        "Ctrl+Shift+H fa la stessa domanda a tutto il progetto. Legge la",
        "query allo stesso modo, con gli stessi due tasti, e i risultati sono",
        "una lista normale: scrivi per restringerla ancora, Invio per aprire",
        "il file a quella riga con il cursore sulla parola. Parte dalla",
        "selezione o dall'ultima cosa scritta in Trova, così cercare la",
        "parola che hai davanti costa un tasto.",
        "",
        "Con Ctrl+N attivo la sostituzione può richiamare i gruppi — cerca",
        "(\\w+)@(\\w+), sostituisci $2.$1 — mentre in una ricerca letterale un",
        "$ resta un dollaro. Sotto i due campi il riquadro mostra la",
        "occorrenza corrente con i gruppi già risolti, e quante altre",
        "farebbero la stessa fine: così Ctrl+A si legge prima di premerlo,",
        "invece di giudicarlo a file già cambiato.",
        "",
        "Un pattern che non compila, o che si arrende prima di finire, lo",
        "dice nel riquadro: scritto a metà non è la stessa cosa di nessun",
        "risultato, e si risolvono in modi diversi.",
        "",
        "La vista divisa (Ctrl+L) dà due pannelli, ognuno con le sue tab:",
        "",
        "  ┌───────────────┬───────────────┐  Alt+← / Alt+→ passano da un",
        "  │ main.rs       │ note.md       │  pannello all'altro. Entrambi",
        "  │               ║               │  eseguono il proprio file con",
        "  │               ║               │  ▶ Esegui; la giunzione",
        "  └───────────────┴───────────────┘  ║ si trascina anche.",
        "",
        "I file modificati fuori vengono ricaricati da soli, a meno che il",
        "buffer abbia modifiche non salvate: in quel caso resta la versione",
        "locale e la status line lo segnala.",
        "",
        "Le barre di scorrimento stanno sull'ultima colonna (e sull'ultima",
        "riga) dentro il riquadro. Compaiono mentre la vista si muove —",
        "comunque si muova: rotellina, frecce, vai alla riga — e di nuovo",
        "appena ci posi sopra il puntatore; per il resto svaniscono. Quella",
        "in basso compare solo con l'a-capo automatico spento: il testo",
        "mandato a capo non ha dove scorrere lateralmente.",
        "",
        "Ferma è solo un cursore che dice dove sei. Puntandola diventa un",
        "comando:",
        "",
        "  · trascina il cursore per scorrere; continua a seguire il mouse",
        "    anche se esce dalla barra",
        "  · clicca un punto qualsiasi della scanalatura per saltarci",
        "  · le ▴ ▾ (e ◂ ▸) alle estremità spostano di una riga per click —",
        "    il lavoro delle frecce da tastiera, fatto col mouse",
        "",
        "Stanno dentro il riquadro e non sul bordo perché il bordo è già la",
        "giunzione che si trascina per ridimensionare: due comandi sulla",
        "stessa colonna renderebbero un terno al lotto mirare all'uno o",
        "all'altro. Quindi una barra visibile copre l'ultima colonna di",
        "testo. Se non c'è niente da scorrere non c'è barra, e quella colonna",
        "torna testo normale.",
    ]),
    ("Terminali", &[
        "I terminali sono pty veri che eseguono la tua $SHELL: ssh, vim,",
        "tmux e claude si comportano come ovunque altrove.",
        "",
        "Ci sono due livelli, e conviene tenerli distinti:",
        "",
        "  finestra   un riquadro affiancato nel layout. Ctrl+Shift+N",
        "             ne apre una.",
        "  tab        una shell dentro una finestra. Ctrl+Shift+T ne apre",
        "             una. La striscia delle tab compare solo",
        "             quando una finestra ne ha due.",
        "",
        "  ┌ Terminale 1 ────────────┬ claude ─┬ octave ──┬───────────────┐",
        "  │ $                       │ la seconda finestra ha tre tab,    │",
        "  │                         │ ognuna con la sua shell; una alla  │",
        "  │                         │ volta è sullo schermo.             │",
        "  └─────────────────────────┴────────────────────────────────────┘",
        "",
        "  Ctrl+PgSu / Ctrl+PgGiù   finestra precedente / successiva",
        "  Ctrl+Shift+← / →         tab precedente / successiva",
        "  Ctrl+Shift+E             dà un nome al terminale e un comando",
        "                           di avvio",
        "",
        "Ctrl+Shift+E apre un form con due campi (Tab cambia campo):",
        "",
        "  Nome                claude",
        "  Comando di avvio    claude",
        "",
        "Il nome sostituisce 'Terminale N' nel titolo o nella tab. Il comando",
        "di avvio viene ricordato insieme al workspace ed eseguito in questa",
        "shell ogni volta che quel workspace viene aperto — vedi la sezione",
        "Workspace. Impostarlo non lo esegue subito.",
        "",
        "Per selezionare testo: trascina col mouse, oppure tieni Shift e usa",
        "le frecce. In entrambi i casi la selezione finisce negli appunti di",
        "sistema, ed Esc la annulla. Per incollare usa il menu contestuale",
        "(Ctrl+V serve alla shell).",
        "",
        "Per tornare indietro nell'output: la rotellina sopra un riquadro",
        "scorre quel che è già uscito dallo schermo, Shift+PagSu/PagGiù fa lo",
        "stesso una schermata per volta, e basta digitare qualcosa per",
        "tornare all'output dal vivo. Una barra sull'ultima colonna del",
        "riquadro dice dove sei — trascinabile, cliccabile, con le frecce",
        "alle estremità, esattamente come quelle dell'editor.",
        "",
        "L'output che arriva mentre stai leggendo indietro non ti porta via",
        "la pagina: la vista resta sulle righe che stai guardando.",
        "",
        "Quanto viene conservato è `terminal_scrollback` in settings.toml,",
        "2000 righe di default. Non è gratis: una shell tiene righe intere di",
        "celle, quindi il costo è righe x colonne x 32 byte, e ogni tab lo",
        "paga per conto suo. Il valore viene letto quando la shell parte,",
        "quindi una modifica vale per le shell che aprirai, non per quelle",
        "già in esecuzione.",
        "",
        "Finché un programma a tutto schermo (vim, less, htop, Claude Code)",
        "tiene lo schermo non c'è una cronologia nostra da scorrere: scorre",
        "una vista sua. Se ha chiesto gli eventi del mouse — quasi tutti lo",
        "fanno — la rotellina gli viene consegnata tacca per tacca, e anche",
        "Shift+PagSu va a lui, così scorre come in qualsiasi altro terminale.",
        "Cosa ne faccia è affar suo: un programma che non scorre con la",
        "rotellina non comincerà a farlo qui.",
        "",
        "Una shell che esce chiude la sua tab, e una finestra rimasta senza",
        "tab sparisce. Un terminale resta sempre aperto.",
    ]),
    ("Workspace", &[
        "Un workspace è la fotografia salvata di un intero assetto:",
        "",
        "  · la radice del progetto e i file aperti nelle tab",
        "  · dimensioni dei frame, quali sono visibili, vista divisa",
        "  · ogni finestra e tab di terminale, con nome, comando di avvio",
        "    e quota di spazio",
        "  · il venv Python selezionato",
        "",
        "  Workspace ▸ Salva workspace...   Ctrl+Shift+W, poi un nome",
        "  Workspace ▸ Apri workspace...     scegli fra quelli salvati",
        "  Workspace ▸ Elimina workspace...  stessa lista, ne toglie uno",
        "",
        "Aprirne uno ricostruisce i terminali che descrive ed esegue ogni",
        "comando di avvio nella sua shell. Un workspace con una shell",
        "chiamata 'claude' e comando 'claude', accanto a una normale e a una",
        "tab 'octave', torna ogni volta esattamente così:",
        "",
        "  ┌ claude ──────────────┬ Terminale 2 ─┬ octave ──────────────┐",
        "  │ $ claude             │ $            │ $ octave             │",
        "  │ ▌                    │              │ octave:1>            │",
        "  └──────────────────────┴──────────────┴──────────────────────┘",
        "",
        "I buffer con modifiche non salvate non vengono mai chiusi",
        "dall'apertura di un workspace: restano aperti accanto ai suoi file.",
        "",
        "Il workspace in uso viene riscritto all'uscita, così un terminale",
        "rinominato o una giunzione spostata si ritrovano al prossimo avvio,",
        "e un `clee` senza argomenti lo riapre. Lanciare clee con un percorso",
        "parte invece da lì e lascia stare il workspace.",
        "",
        "Cambiare cartella di progetto — Invio su una directory nell'albero,",
        "o risalire da essa — esce dal workspace: il badge sparisce e il suo",
        "file resta intatto, a descrivere il progetto da cui vieni. Per",
        "tornarci lo riapri dal menu Workspace, da qualsiasi cartella. Fa",
        "eccezione il layout predefinito: non appartiene a nessun progetto,",
        "quindi ti segue.",
        "",
        "Ogni workspace è un file TOML nella cartella di configurazione",
        "(workspaces/<nome>.toml): si può modificare a mano, copiare su",
        "un'altra macchina o tenere in un repo di dotfile.",
        "",
        "Tre workspace sono predefiniti e non sono file: Default layout, che",
        "rimette le cornici come le spedisce CleeCode, e due che preparano",
        "una sessione di calcolo:",
        "",
        "  clee -w octave    un prompt Octave, già avviato",
        "  clee -w pylab     uno Python, nel venv attivo se ce n'è uno",
        "",
        "Ognuno apre una finestra terminale con due schede — l'interprete e",
        "una shell semplice per git e pip. Una seconda finestra toglierebbe",
        "schermo all'editor per sempre per tenerci una cosa che si usa un",
        "minuto alla volta; una scheda è a un tasto di distanza e non costa",
        "niente.",
        "",
        "Ognuno apre anche una seconda finestra terminale col workspace: le",
        "variabili di quella sessione, con dimensioni, minimo, massimo e",
        "media. Si riempie da sola ogni volta che un comando finisce — al",
        "tuo prompt non viene digitato niente per chiederlo, quindi la",
        "trascrizione resta tua e un interprete occupato non viene mai",
        "interrotto. Una finestra e non una scheda, perché il senso è",
        "guardarla di sfuggita mentre lavori.",
        "",
        "Un grafico si apre come tab accanto allo script che l'ha disegnato,",
        "e non si apre nessuna finestra da nessuna parte: una figura viva non",
        "si può spostare dentro un terminale, quindi alla sessione viene detto",
        "di non aprirne e consegna un'immagine. Ridisegna e la tab cambia con",
        "lei; una seconda figura è una seconda tab. Non ti toglie mai la",
        "tastiera da quello che stavi scrivendo.",
        "",
        "Non si installa niente e non si scrive niente nella tua home.",
        "All'interprete arrivano il codice e un percorso su cui scrivere",
        "tramite l'ambiente, e fuori da CleeCode non fanno nulla.",
        "",
        "Il prompt va accanto all'editor quando la finestra è larga abbastanza",
        "per entrambi, che è dove lo mettono i desktop di Octave e MATLAB e",
        "per lo stesso motivo: l'output numerico è largo, e una riga di",
        "matrice in un pannello stretto va a capo diventando illeggibile.",
        "Sotto le 150 colonne circa va sotto, così nessuna delle due cornici",
        "viene schiacciata.",
        "",
        "Quei tre nomi sono riservati e salvarci sopra viene rifiutato. Un",
        "workspace tuo che aveva già quel nome si apre lo stesso e vince —",
        "CleeCode te lo dice, così puoi rinominare il tuo se quello che",
        "volevi era il preset.",
    ]),
    ("Esecuzione", &[
        "▶ Esegui nella toolbar, o Ctrl+Shift+R, esegue il file dell'editor",
        "sotto focus: il comando viene scritto in un terminale libero, quindi",
        "output, prompt ed errori sono normale output di shell, scorribile e",
        "copiabile.",
        "",
        "Il pulsante a sinistra di ▶ Esegui dice, per il file che hai davanti,",
        "cosa userà Esegui su di lui — e permette di cambiarlo. Quel che offre",
        "segue l'estensione, così non è mai un comando che non fa niente:",
        "",
        "  · Su un file .py è il selettore di venv Python: quelli trovati",
        "    nella radice del progetto più quelli registrati da altrove (per",
        "    percorso o col browser di cartelle). Quello scelto sostituisce",
        "    python/python3 nel comando ed è ricordato nel workspace. Per",
        "    ogni altro interprete un venv non vuol dire niente, ed è il",
        "    motivo per cui non compare altrove.",
        "  · Su ogni tipo di file, .py compreso, l'ultima voce apre il comando",
        "    di esecuzione di quell'estensione. È così che un tipo di file a",
        "    cui nessuno aveva pensato — .tex, .rs, .sql — ne ottiene uno.",
        "",
        "Un comando può stare in due file, e il menu li propone entrambi con",
        "un ● su quello che Esegui userà davvero:",
        "",
        "  settings.toml     condiviso da tutti i progetti",
        "  .cleecode.toml    nella radice del progetto, e solo per lui",
        "",
        "Dove il file di progetto dice qualcosa, vince lui. È quello che",
        "permette a un progetto di compilare il proprio master — latexmk",
        "-pdf tesi.tex — mentre tutti gli altri .tex continuano a usare il",
        "comando condiviso. Svuotare quella casella toglie l'eccezione e",
        "restituisce l'estensione al comando condiviso; svuotare invece",
        "quella condivisa fa tornare il predefinito di serie.",
        "",
        ".cleecode.toml appartiene al progetto, quindi è fatto per essere",
        "committato: chi apre la cartella si trova gli stessi comandi. Viene",
        "cancellato quando sparisce la sua ultima eccezione, invece di",
        "restare lì come file vuoto.",
        "",
        "Entrambi usano la stessa tabella [run_commands], per estensione, ed",
        "è esattamente quella che la finestrella scrive:",
        "",
        "  [run_commands]",
        "  py  = \"python3 {file}\"",
        "  m   = \"octave --persist {file}\"",
        "  tex = \"pdflatex -output-directory {dir} {file}\"",
        "",
        "Quattro segnaposto, ognuno già quotato perché i percorsi con spazi",
        "sopravvivano:",
        "",
        "  {file}  il percorso intero    {name}  il nome del file",
        "  {dir}   la sua cartella       {stem}  quel nome senza .est",
        "",
        "Il comando viene scritto in una shell vera, quindi i passaggi si",
        "concatenano come si leggono: \"pdflatex {file} && open {dir}/{stem}.pdf\".",
        "",
        "Anche le immagini si possono eseguire: .png, .jpg, .gif e .webp",
        "hanno un comando che le mostra in un terminale con chafa. Non è però",
        "così che si aprono — vedi la sezione Immagini — serve per quando la",
        "vuoi in un terminale invece che in una tab. Ogni altro file che non",
        "sia testo ma abbia un comando viene eseguito all'apertura.",
        "Il -f symbols in quel comando è essenziale: lasciato a sé,",
        "chafa chiede al terminale ospite cosa sa fare, si sente rispondere",
        "'grafica', e manda un'immagine che un riquadro non può inoltrare,",
        "lasciandolo vuoto. Un'immagine più alta del riquadro si scorre",
        "all'indietro come qualsiasi altro output.",
        "",
        "Due casi particolari fanno risparmiare parecchi fastidi:",
        "",
        "  · Un interprete installato fuori dal PATH va in",
        "    [interpreter_paths] (nome programma -> percorso assoluto).",
        "    Octave su Windows viene trovato da solo in Program Files.",
        "  · Se un prompt Octave è già aperto in un terminale, un file .m",
        "    viene passato a quella sessione con run(...) invece di avviare",
        "    un secondo interprete: variabili e finestre dei grafici restano.",
    ]),
    ("Immagini", &[
        "Un'immagine si apre in una tab e viene disegnata lì. Non c'è niente",
        "da modificare, quindi non le viene creato nessun buffer: la tab è",
        "l'immagine.",
        "",
        "  .png .jpg .jpeg .gif .webp .bmp .ico .tiff",
        "",
        "Quanto bene venga disegnata dipende dal terminale in cui gira",
        "CleeCode. Dove c'è un protocollo grafico — kitty, iTerm2, sixel —",
        "sono pixel veri. Dove non c'è, si ripiega su mezzi blocchi colorati.",
        "La status line dice quale dei due hai avuto quando la tab si apre,",
        "così un'immagine grossolana non è mai un mistero.",
        "",
        "I pixel li disegna CleeCode, non un programma dentro un riquadro",
        "terminale. Un riquadro non può mostrarli affatto: viene tradotto in",
        "una griglia di celle e ridipinto, e le sequenze grafiche non",
        "sopravvivono a quel passaggio. Disegnate dall'editor escono come",
        "tutto il resto — ed è anche il motivo per cui funziona via ssh.",
        "",
        "Le immagini grandi vengono decodificate su un thread separato, così",
        "aprirne una non blocca mai la finestra né le shell dentro. Quelle",
        "assurdamente grandi vengono rifiutate con un messaggio invece che",
        "tentate.",
        "",
        "In vista divisa un'immagine si apre nel pannello in cui non stai",
        "lavorando, così il file da cui vieni resta visibile. Il layout non",
        "viene mai riorganizzato per te.",
    ]),
    ("Markdown", &[
        "Un file markdown si apre come testo, perché è quello che ci fai.",
        "\u{25b6} Esegui te lo mostra reso, nell'altra metà dell'editor —",
        "dividendola se non lo era già, perché chiedere un'anteprima è",
        "chiedere di vedere due cose insieme.",
        "",
        "Due tab, un file, una sola copia del testo: la tab resa non possiede",
        "niente, è una vista del buffer in cui stai scrivendo. Non possono",
        "dire cose diverse sullo stesso file, e chiudere il sorgente chiude",
        "anche la vista. Nella striscia si distinguono da un glifo:",
        "",
        "  guida.md      il sorgente, quello che modifichi",
        "  \u{25a4} guida.md    la vista resa",
        "",
        "Segue quello che scrivi. Dove il terminale sa disegnare immagini ed",
        "è installato pandoc, il reso è un documento vero: font veri, e le",
        "immagini richiamate dal testo che compaiono nel flusso — cosa che",
        "una griglia di caratteri non sa fare. Ci vuole circa mezzo secondo,",
        "quindi aspetta che tu smetta di scrivere invece di inseguire i",
        "tasti.",
        "",
        "Se manca una delle due cose, ripiega sul testo di terminale con gli",
        "stili — titoli, liste, citazioni, blocchi di codice, enfasi. Più",
        "grezzo, ma sta dietro ai tasti e funziona via ssh su qualsiasi cosa.",
        "",
        "\u{25b6} Esegui su una tab resa diventa Aggiorna, e lo forza.",
        "",
        "Ogni anteprima ha una barra in basso. I pulsanti sono anche tasti —",
        "in un'anteprima non si digita, quindi le lettere semplici erano",
        "libere:",
        "",
        "  \u{2190} \u{2192}    pagina precedente / successiva (documenti)",
        "  g      vai a una pagina",
        "  + -    ingrandisci / rimpicciolisci",
        "  f      adatta la pagina intera",
        "  w      adatta la larghezza, che è quel che serve per leggere",
        "  d      scuro: la pagina invertita, per un documento chiaro di notte",
        "  i      inverti: lo stesso, su un'immagine, dov'è un negativo",
        "  t      testo: il markdown come testo colorato invece che documento",
        "",
        "Lo scuro viene ricordato, separatamente per i PDF e per il markdown",
        "— un articolo e un README si leggono in posti diversi — quindi",
        "attivarlo una volta apre così anche il prossimo dello stesso tipo.",
        "Un'immagine non è nessuno dei due: invertire una fotografia non è una",
        "modalità ma il negativo di quella singola immagine, così si chiama",
        "inverti, resta sulla sua tab e non passa mai all'immagine dopo.",
        "",
        "Il pulsante testo è solo del markdown, e solo dove un documento si",
        "può davvero fare: scambia le due rese, e viene ricordato come il",
        "resto. Sul testo colorato la barra non porta altro — lì non ci sono",
        "pixel da ingrandire, adattare o scurire.",
        "",
        "Ingrandita oltre il riquadro, la pagina si scorre invece di essere",
        "rimpicciolita: rotellina e frecce spostano la finestra su di lei, le",
        "barre dicono dove sei e si trascinano, e Ctrl con la rotellina",
        "ingrandisce invece di spostare.",
    ]),
    ("PDF", &[
        "Un PDF si apre a pagine, una per volta, disegnate come un'immagine",
        "— pixel veri dove il terminale ha un protocollo grafico.",
        "",
        "  \u{2190} \u{2191}   pagina precedente",
        "  \u{2192} \u{2193}   pagina successiva",
        "",
        "Le frecce semplici, senza accordi da ricordare: nella tab non c'è",
        "testo in cui muovere un cursore, quindi erano libere. La pagina in",
        "cui sei è scritta in basso nel riquadro.",
        "",
        "Le pagine vengono rasterizzate da pdftoppm (poppler) o, in mancanza,",
        "da ghostscript — quello che trova. Nessuno dei due è incluso: un",
        "renderer PDF che CleeCode possa linkare o ha una licenza che questo",
        "progetto non può prendersi, o è un blob binario precompilato per",
        "piattaforma. Se non c'è nessuno dei due la tab lo dice, invece di",
        "restare vuota. Una distribuzione TeX si porta dietro ghostscript,",
        "quindi se sei qui per LaTeX ce l'hai già.",
        "",
        "Un PDF che cambia su disco viene rigenerato dov'è, sulla pagina che",
        "stavi leggendo. È il ciclo LaTeX: modifichi il sorgente, premi",
        "\u{25b6} Esegui, e la pagina accanto diventa quella appena composta",
        "— col sorgente ancora a schermo, se prima dividi l'editor.",
    ]),
    ("Tasti", &[
        "La navigazione fra frame è Ctrl+Alt più una freccia, non solo Ctrl:",
        "macOS assegna Ctrl con ogni freccia a Mission Control e al cambio di",
        "Spazio, e le intercetta prima che il terminale le veda.",
        "",
        "Niente tasti funzione e niente PagSu/PagGiù: su un portatile vogliono",
        "tutti il tasto Fn. Il layer dell'applicazione è Ctrl+Shift+<lettera>,",
        "ed è sicuro dentro un terminale — nessun terminale sa mandare",
        "Ctrl+Shift al programma in esecuzione, quindi lì non lo ascolta nessuno.",
        "",
        "Generali",
        "  Ctrl+Shift+M            questo manuale",
        "  Ctrl+Shift+B            barra dei menu",
        "  Ctrl+Shift+O            impostazioni",
        "  Ctrl+Shift+G            menu contestuale del frame sotto focus",
        "  Ctrl+P / Ctrl+O         palette comandi / apertura rapida",
        "  Ctrl+Q                  esci",
        "",
        "Focus e layout",
        "  Ctrl+Alt+←↑↓→           va al frame in quella direzione",
        "  Ctrl+Tab                oppure li scorre, come Cmd+Tab",
        "  Ctrl+Shift+← / →        tab precedente / successiva del frame",
        "  Ctrl+E / Ctrl+J         sidebar / pannello terminali",
        "  Ctrl+B / Ctrl+L         barra dei menu / editor affiancati",
        "  Alt+← / Alt+→           fra i due pannelli",
        "  Ctrl+Shift+U            modalità ridimensiona",
        "",
        "File e modifica",
        "  Ctrl+S / Ctrl+Shift+S   salva / salva tutto",
        "  Ctrl+W / Ctrl+D         chiude la tab",
        "  Ctrl+Z / Ctrl+Y         annulla / ripeti",
        "  Ctrl+F / Ctrl+G         trova e sostituisci / vai alla riga",
        "  Ctrl+U / Ctrl+N         in Trova: maiuscole / regex",
        "  Ctrl+Shift+H            cerca in tutto il progetto",
        "  Ctrl+Shift+D            pannello Git (modifiche, cronologia, branch)",
        "  Ctrl+K                  commenta",
        "  ↑↓ Tab Invio Esc        nella lista dei completamenti, se aperta",
        "  Alt+↑ / Alt+↓           sposta riga    Alt+Shift+↓  duplica",
        "  Ctrl+Shift+F            comprimi / espandi",
        "",
        "Terminali",
        "  Ctrl+Shift+T            nuova tab",
        "  Ctrl+Shift+K            chiude questa shell (e la finestra se sola)",
        "  Ctrl+Shift+N            nuova finestra",
        "  Ctrl+Shift+↑ / ↓        finestra precedente / successiva",
        "  Ctrl+Shift+E            nome e comando di avvio",
        "  Shift+frecce            seleziona testo (copia mentre selezioni)",
        "",
        "Workspace ed esecuzione",
        "  Ctrl+Shift+R            esegue il file corrente",
        "  Ctrl+Shift+X            esegue la selezione o la cella",
        "  Ctrl+Shift+W            salva il workspace",
        "",
        "Nell'albero: n / N nuovo file / cartella, e rinomina, Canc elimina,",
        "H file nascosti, Invio apre o cambia radice.",
        "",
        "Gli unici Alt rimasti sono le frecce, e funzionano ovunque: Option",
        "con una freccia non produce nessun carattere, quindi ogni terminale",
        "la inoltra come Meta qualunque sia il layout.",
    ]),
    ("File", &[
        "Tutto quello che CleeCode conserva sta in una sola cartella:",
        "",
        "  ~/.config/cleecode/            (macOS e Linux)",
        "  %APPDATA%\\cleecode\\             (Windows)",
        "",
        "    settings.toml                preferenze, layout, comandi di",
        "                                 esecuzione, venv registrati,",
        "                                 ultima sessione",
        "    workspaces/<nome>.toml       un file per workspace salvato",
        "",
        "settings.toml è pensato per essere modificato a mano. Le parti che",
        "non hanno un pannello nell'app sono tutte lì: [run_commands],",
        "[interpreter_paths], registered_venvs, auto_pairs, completion,",
        "diagnostics.",
        "",
        "Le impostazioni (Ctrl+Shift+O) coprono numeri di riga, evidenziazione,",
        "a capo automatico, ampiezza tab, spazi o tab, marcatori degli spazi,",
        "indentazione automatica, mouse e lingua dell'interfaccia. Le",
        "modifiche valgono subito e vengono salvate all'uscita.",
        "",
        "Riga di comando:",
        "  clee                  riprende l'ultimo workspace o progetto",
        "  clee <cartella>       la apre come radice del progetto",
        "  clee <file>           apre il file nella cartella corrente",
        "  clee --install-font   installa il Nerd Font incluso",
        "  clee --help           uso, --version",
    ]),
];

#[cfg(test)]
mod tests {
    use super::*;

    /// The reading pane is the modal minus the section list; lines longer than that would be
    /// clipped mid-diagram, which is exactly what the ASCII pictures can't survive.
    #[test]
    fn every_line_fits_the_reading_pane() {
        const MAX: usize = 76;
        for lang in [Lang::En, Lang::It] {
            for section in sections(lang) {
                assert!(section.title.chars().count() <= 14, "section title is too long for the list");
                for line in section.body {
                    assert!(
                        line.chars().count() <= MAX,
                        "manual line is {} columns, over the {MAX} the pane can show: {line}",
                        line.chars().count()
                    );
                }
            }
        }
    }

    /// The diagrams are drawn by hand, and a single stray column makes a box visibly crooked —
    /// which is how a double-width emoji got into one of them. Within a run of box-drawing
    /// lines, the left edges must share a column and the right edges (the lines that close with
    /// a box character, rather than trailing into prose) must share a width.
    #[test]
    fn diagram_boxes_line_up() {
        const EDGES: [char; 8] = ['┌', '┐', '└', '┘', '├', '┤', '│', '╔'];
        let starts_box = |l: &&str| l.trim_start().starts_with(EDGES);
        for lang in [Lang::En, Lang::It] {
            for section in sections(lang) {
                let mut block: Vec<&str> = Vec::new();
                // A trailing blank flushes the last block without duplicating the check.
                for line in section.body.iter().copied().chain(std::iter::once("")) {
                    if starts_box(&line) {
                        block.push(line);
                        continue;
                    }
                    if block.len() > 1 {
                        let indent = |l: &str| l.chars().take_while(|c| *c == ' ').count();
                        let left = indent(block[0]);
                        let closed: Vec<&&str> =
                            block.iter().filter(|l| l.ends_with(EDGES)).collect();
                        let width = closed.first().map(|l| l.chars().count()).unwrap_or(0);
                        for l in &block {
                            assert_eq!(indent(l), left, "diagram line starts in the wrong column: {l}");
                        }
                        for l in closed {
                            assert_eq!(l.chars().count(), width, "diagram box is not rectangular: {l}");
                        }
                    }
                    block.clear();
                }
            }
        }
    }

    /// Both languages must offer the same sections, or switching language mid-read would land
    /// the reader somewhere else entirely.
    #[test]
    fn both_languages_have_the_same_sections() {
        assert_eq!(sections(Lang::En).len(), sections(Lang::It).len());
        assert!(!sections(Lang::En).is_empty());
    }

    #[test]
    fn scrolling_stops_at_the_last_screenful_and_at_the_top() {
        let mut state = ManualState::new();
        // 40 lines in a 10-row pane: the furthest down is line 30.
        state.scroll_by(100, 40, 10);
        assert_eq!(state.scroll, 30);
        state.scroll_by(-100, 40, 10);
        assert_eq!(state.scroll, 0);
        // Shorter than the pane: nothing to scroll.
        state.scroll_by(5, 4, 10);
        assert_eq!(state.scroll, 0);
    }

    #[test]
    fn changing_section_returns_to_its_top() {
        let mut state = ManualState::new();
        state.scroll_by(5, 40, 10);
        state.cycle(1, 3);
        assert_eq!((state.section, state.scroll), (1, 0));
        // Wraps in both directions.
        state.cycle(-1, 3);
        assert_eq!(state.section, 0);
        state.cycle(-1, 3);
        assert_eq!(state.section, 2);
        // Out-of-range clicks land on the last section rather than panicking.
        state.select(99, 3);
        assert_eq!(state.section, 2);
    }
}
